#!/usr/bin/env python3

import argparse

from library import workflow



def _build_parser_() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="aw-run", description="AetherWeave runner")
 
    subparsers = parser.add_subparsers(title="subcommands", required=True)

    workflow_parser = subparsers.add_parser("workflow", help="run a workflow")
    workflow_parser.add_argument("--name", required=True, type=str)
    workflow_parser.set_defaults(run=workflow.run)

    return parser


if __name__ == "__main__":
    runner = _build_parser_().parse_args()

    runner.run(**runner.__dict__)
